# Generated by Django 4.2.8 on 2024-01-08 15:32

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbroadTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism, familiyasi:")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email:')),
                ('number', models.CharField(max_length=40, verbose_name='Raqamizgizni kiriting:')),
                ('ticket', models.CharField(choices=[('Tickets Type 1', 'Tickets Type 1'), ('Tickets Type 2', 'Tickets Type 2'), ('Tickets Type 3', 'Tickets Type 3')], default='Tickets Type 1', max_length=20, verbose_name='Chipta:')),
                ('adult', models.CharField(choices=[('Adult', 'Adult'), ('one', 1), ('two', 2), ('three', 3)], default=1, max_length=20, verbose_name='Kottalar:')),
                ('child', models.CharField(choices=[('Child', 'Child'), ('one', 1), ('two', 2), ('three', 3)], default=1, max_length=20, verbose_name='Bolalar:')),
                ('message', models.CharField(max_length=500, verbose_name='Kelgan xabarlar:')),
                ('created_at', models.DateField()),
            ],
            options={
                'verbose_name': 'hotel_buyurtma_qilish_',
            },
        ),
        migrations.CreateModel(
            name='Cites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Shahar_',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Mehmonxona_',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='note/')),
            ],
            options={
                'verbose_name': 'Rasm_',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=40, verbose_name='dam olish kunlari:')),
                ('image1', models.ImageField(upload_to='yes/', verbose_name='joy rasmi:')),
                ('price', models.FloatField()),
                ('location', models.URLField(max_length=4000, verbose_name='Lokatsiya::')),
                ('created_at', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='opinion.cites')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='opinion.hotels')),
                ('image', models.ManyToManyField(related_name='image', to='opinion.images', verbose_name='rasmlar')),
            ],
            options={
                'verbose_name': 'Sayohat_',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TourTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Mashxur joy nomi:')),
                ('body', models.TextField(verbose_name='joy haqida malumot:')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='opinion.tour')),
            ],
            options={
                'verbose_name': 'Sayohat_ Translation',
                'db_table': 'opinion_tour_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HotelsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Mehmonxona')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='opinion.hotels')),
            ],
            options={
                'verbose_name': 'Mehmonxona_ Translation',
                'db_table': 'opinion_hotels_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CitesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Shahar nomi:')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='opinion.cites')),
            ],
            options={
                'verbose_name': 'Shahar_ Translation',
                'db_table': 'opinion_cites_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
