# Generated by Django 4.2.8 on 2024-02-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_one', models.CharField(max_length=200, verbose_name='Telefon number 1:')),
                ('number_two', models.CharField(max_length=200, verbose_name='Telefon number 2:')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email nomi:')),
                ('address', models.CharField(max_length=300, verbose_name='Address nomi:')),
                ('whatsapp', models.URLField(max_length=4000, verbose_name='whatsapp link:')),
                ('facebook', models.URLField(max_length=4000, verbose_name='Facebook link:')),
                ('telegram', models.URLField(max_length=4000, verbose_name='Telegram  link:')),
                ('youtobe', models.URLField(max_length=4000, verbose_name='You tobe  link:')),
                ('instagram', models.URLField(max_length=4000, verbose_name='Instagram  link:')),
            ],
            options={
                'verbose_name': 'Link_nomlar_',
            },
        ),
    ]
