# Generated by Django 4.2.8 on 2024-01-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sayohat nomi:')),
            ],
            options={
                'verbose_name': 'Tags_turi_',
            },
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200, verbose_name='Sayohat nomi:')),
            ],
            options={
                'verbose_name': 'Sayohat_turi_',
            },
        ),
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_name', models.ManyToManyField(related_name='not_name', to='type.tourcategory', verbose_name='Tour')),
            ],
            options={
                'verbose_name': 'Paket_tur_',
            },
        ),
        migrations.CreateModel(
            name='TagsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_name1', models.ManyToManyField(related_name='not_name1', to='type.tagscategory', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Tag_tur_',
            },
        ),
    ]
